name: Publish VSCode Extension

on:
    push:
        branches:
            - main

jobs:
    publish:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 18

            - name: Install Dependencies
              run: npm i

            - name: Package Extension
              run: npx vsce package

            - name: Check if extension is already published
              run: |
                  VERSION=$(node -p "require('./package.json').version")
                  echo "Version: $VERSION"
                  echo "Checking if version is already published..."
                  npx vsce show wakeupingear.petalburg | grep $VERSION
                  if [ $? -eq 0 ]; then
                    echo "Version $VERSION is already published. Skipping publish."
                    exit 0
                  fi
                    echo "Publishing version $VERSION..."

            - name: Publish Extension
              env:
                  VSCE_PAT: ${{ secrets.VSCE_TOKEN }}
              run: npx vsce publish -p $VSCE_TOKEN
